symb = {'L01cg', 'L02cg', 'L03cg', ...
        'L11cg', 'L12cg', 'L13cg', ...
        'L21cg', 'L22cg', 'L23cg', ...
        'L01', 'L02', 'L03', ...
        'L11', 'L12', 'L13', ...
        'L21', 'L22', 'L23', ...
        'Le1', 'Le2', 'Le3', ...
        'deltaecg', 'Lecg', ...      
        'beta1', 'beta2', 'beta3', ...
        'gamma1', 'gamma2', 'gamma3', ...
        'm11', 'm12', 'm13', ...
        'm21', 'm22', 'm23', 'me', ...
        'J11', 'J12', 'J13', ...
        'J21', 'J22', 'J23', 'Je', ... 
        '\mathrm{xpp}', '\mathrm{ypp}', '\mathrm{alphapp}', ...
        '\mathrm{xp}', '\mathrm{yp}', '\mathrm{alphap}', ...
        'y\!\left(t\right)', 'y\!\left(t\right)', '\mathrm{alpha}'...       
        '\mathrm{th11pp}', '\mathrm{th12pp}', '\mathrm{th13pp}', ...
        '\mathrm{th11p}', '\mathrm{th12p}', '\mathrm{th13p}', ...
        'th11', 'th12', 'th13', ...
        '\mathrm{th21pp}', '\mathrm{th22pp}', '\mathrm{th23pp}', ...
        '\mathrm{th21p}', '\mathrm{th22p}', '\mathrm{th23p}', ...
        'th21', 'th22', 'th23', '\!\left(t\right)'};


latexvar = {'L_{01}^{cg}', 'L_{02}^{cg}', 'L_{03}^{cg}', ...
            'L_{11}^{cg}', 'L_{12}^{cg}', 'L_{13}^{cg}', ...
            'L_{21}^{cg}', 'L_{22}^{cg}', 'L_{23}^{cg}', ...
            'L_{01}', 'L_{02}', 'L_{03}', ...
            'L_{11}', 'L_{12}', 'L_{13}', ...
            'L_{21}', 'L_{22}', 'L_{23}', ...
            'L_{e}^1', 'L_{e}^2', 'L_{e}^3', ...
            '\delta_{e}^{cg}', 'L_{e}^{cg}', ...
            '\beta_1', '\beta_2', '\beta_3', ...
            '\gamma_1', '\gamma_2', '\gamma_3', ...
            'm_{11}', 'm_{12}', 'm_{13}', ...
            'm_{21}', 'm_{22}', 'm_{23}', 'm_e', ...
            'J_{11}', 'J_{12}', 'J_{13}', ...
            'J_{21}', 'J_{22}', 'J_{23}', 'J_e', ... 
            'x', 'y', '\alpha', ...
            '\mathrm{\dot x}', '\mathrm{\dot y}', '\mathrm{\dot \alpha}', ...
            '\mathrm{\ddot x}', '\mathrm{\ddot y}', '\mathrm{\ddot \alpha}', ...
            '\theta_{11}', '\theta_{12}', '\theta_{13}', ...
            '\dot \theta_{11}', '\dot \theta_{12}', '\dot \theta_{13}', ...
            '\ddot \theta_{11}', '\ddot \theta_{12]', '\ddot \theta_{13}', ...
            '\theta_{21}', '\theta_{22}', '\theta_{23}', ...
            '\dot \theta_{21}', '\dot \theta_{22}', '\dot \theta_{23}', ...
            '\ddot \theta_{21}', '\ddot \theta_{22}', '\ddot \theta_{23}', ''};

% Latex pretty model
pretty_str = latex_model(eqdyn, symb, latexvar);

% Save on file
fid = fopen('pretty_model.txt','wt');
fprintf(fid, '%s', pretty_str);
fclose(fid);