% Position constraint - Equality
eqn_q1top = eqn_con1 == 0;
eqn_q2toq1_p = eqn_con2 == 0;

temp_eqn_q1top = subs(eqn_q2toq1_p, [x, y, alpha], sym('x', [1, 3]));
temp_eqn_q1top = expand(temp_eqn_q1top);
sol_eqn_q1top = solve(temp_eqn_q1top, sym('x', [1, 3]), 'ReturnConditions', true);

% Velocity constraint - Differentiation
eqn_q1ptopp = diff(eqn_q1top, t);
eqn_q1ptopp = subs(eqn_q1ptopp, diff2p, varp);

% Solution for motor velocities
temp_eqn_q1ptopp = subs(eqn_q1ptopp, [th11p, th12p, th13p], ...
                         sym('x', [1, 3]));
solq1ptopp = solve(temp_eqn_q1ptopp, sym('x', [1, 3]), ...
                   'ReturnConditions', true);

eqn_q2toq1p_pp = diff(eqn_q2toq1_p, t);
eqn_q2toq1p_pp = subs(eqn_q2toq1p_pp, diff2p, varp);

temp_eqn_q2ptoq1p_pp = subs(eqn_q2toq1p_pp, ...
                            [th21p, th22p, th23p], ...
                            sym('x', [1, 3]));
solq2ptoq1p_pp = solve(temp_eqn_q2ptoq1p_pp, ...
                     sym('x', [1, 3]), ...
                     'ReturnConditions', true);

% Acceleration constraint - Differentiation
eqn_q1pptoppp = diff(eqn_q1ptopp, t);
eqn_q1pptoppp = subs(eqn_q1pptoppp, ...
                     [diff2p, diff2pp], ...
                     [varp, varpp]);
temp_eqn_q1ptoppp = subs(eqn_q1pptoppp, ...
                         [th11pp, th12pp, th13pp], ...
                         sym('x', [1, 3]));

solq1pptoppp = solve(temp_eqn_q1ptoppp, sym('x', [1, 3]), ...
                     'ReturnConditions', true);


eqn_q2toq1pp_ppp = diff(eqn_q2toq1p_pp, t);
eqn_q2toq1ppp_ppp = subs(eqn_q2toq1pp_ppp, ...
                         [diff2p, diff2pp], ...
                         [varp, varpp]);

temp_eqn_q2toq1ppp_ppp = subs(eqn_q2toq1ppp_ppp, ...
                         [th21pp, th22pp, th23pp], ...
                         sym('x', [1, 3]));


solq2toq1pp_ppp  = solve(temp_eqn_q2toq1ppp_ppp, sym('x', [1, 3]), ...
                         'ReturnConditions', true);