function sys = numerize_pendulum(sys, WP)
    
    % Symbols to substitute
    symbs = [sys.syms, ...
             sys.bodies{1}.syms, ...
             sys.bodies{2}.syms(1,1), ...
             sys.bodies{2}.syms(3,4), sys.bodies{2}.syms(1,5), ...
             sys.bodies{2}.syms(1,6), sys.bodies{2}.syms(1,7), ...
             sys.bodies{3}.syms(1,1), ...
             sys.bodies{3}.syms(3,4), sys.bodies{3}.syms(1,5), ...
             sys.bodies{3}.syms(1,6), sys.bodies{3}.syms(1,7)];
    
     length(sys.params)
     length(symbs)
         
    % Linearized functions
    sys.A_num = double(subs(sys.A, symbs, sys.params));
    sys.B_num = double(subs(sys.B, symbs, sys.params));
    sys.C_num = double(subs(sys.C, symbs, sys.params));
    sys.D_num = double(subs(sys.D, symbs, sys.params));

end