function out1 = pendulumfun(x, xp, th1, th1p, PWM)
%PENDULUMFUN
%    OUT1 = PENDULUMFUN(PWM,TH1,TH1P,XP)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    18-Mar-2019 11:28:33

t2 = cos(th1);
t3 = sin(th1);
t4 = t2.^2;
t5 = t4.*6.29978758919307e-4;
t6 = t5-2.846505689340844e-3;
t7 = 1.0./t6;
t8 = th1p.^2;
out1 = [xp;th1p;t7.*(PWM.*5.616792658798517e-4-xp.*5.43146455983167e-4+t2.*t3.*7.567982205300306e-6+t3.*t8.*1.476890973220672e-7+t2.*th1p.*3.076741952069184e-7).*-8.157777951810374e2;t7.*(t3.*1.788017818025486e-4+th1p.*7.26913632e-6+PWM.*t2.*2.936932619542769e-3-t2.*xp.*2.840027468821038e-3+t2.*t3.*t8.*7.722430821735006e-7).*8.157777951810374e2];
