params = catstruct(params, sys.params_str);
mdlname = 'sim_single_lin';
open_system(mdlname);
set_param(mdlname, 'SaveOutput', 'on');
simOut_lin = sim(mdlname, 'SrcWorkspace', 'current', ...
                          'AbsTol', '1e-8', ...
                          'RelTol', '1e-8', ...
                          'StartTime','0',...
                          'StopTime',num2str(params.tf),...
                          'FixedStep','1e-3');

params = catstruct(params, sys.params_str);
mdlname = 'sim_single_nlin';
open_system(mdlname);
set_param(mdlname, 'SaveOutput', 'on');
simOut_nlin = sim(mdlname, 'SrcWorkspace', 'current', ...
                          'AbsTol', '1e-8', ...
                          'RelTol', '1e-8', ...
                          'StartTime','0',...
                          'StopTime',num2str(params.tf),...
                          'FixedStep','1e-3');

